# Disallowing packages: openvpn
# If you require these packages, please review the package approval process at: https://github.com/travis-ci/apt-package-whitelist#package-approval-process
#addons:
#    apt:
#        sources:
#            - ubuntu-toolchain-r-test
#        packages:
#            - openvpn
dist: focal

jobs:
  - arch: amd64
  - group: edge
    virt: vm
    arch: arm64-graviton2
 
services:
    - docker

before_install:
    - docker --version

install:
    - git clone https://github.com/docker-library/official-images.git official-images

# Assist with ci test debugging:
#   - DEBUG=1
before_script:
    - image="kylemanna/openvpn"
    - docker build -t "$image" .
    - docker inspect "$image"
    - docker run --rm "$image" openvpn --version || true # why does it return 1?
    - docker run --rm "$image" openssl version

script:
    - official-images/test/run.sh "$image"
    - test/run.sh "$image"
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - if [ "${TRAVIS_CPU_ARCH}" == "arm64" ]; then
      docker tag $image:latest ab1997/openvpn:$TRAVIS_BRANCH-arm64;
      docker push ab1997/openvpn:$TRAVIS_BRANCH-arm64;
      else
      docker tag $image:latest ab1997/openvpn:$TRAVIS_BRANCH;
      docker push ab1997/openvpn:$TRAVIS_BRANCH;
      fi

after_script:
    - docker images
